### ISSUE TITLE
Following instructions doesn't work

### ISSUE THREAD

**Issue by quikwert** [gschwaer/Swappy#1]
I perform startup procedure but jump doesn't appear.
Actgions step by step.

Lload on
0100
clk on
1100
clk off
000 clk on
lload off
clk off

HELP

**Comment by gschwaer** [comment]
Hi, 

I see now, there is a problem in how I described the loading procedure:

> The program code is loaded the same way: set Iload, set value, toggle CLK, repeat, ... unset Iload.

With "toggle" I meant `CLK` on __and off again__ (!). But that was certainly described badly, sorry (I will correct that).

However, I tried to test the project myself again and couldn't get it to work! I don't really understand what the problem is right now. Unfortunately it is currently impossible to edit chips in the simulator so I cannot debug the problem. I tried to load the project in the [community edition simulator](https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE) (which supposedly has chip editing capability), but it didn't load. I will wait for this issue to be resolved and try again: https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/issues/33

**Comment by quikwert** [comment]
> Hi,
> 
> I see now, there is a problem in how I described the loading procedure:
> 
> > The program code is loaded the same way: set Iload, set value, toggle CLK, repeat, ... unset Iload.
> 
> With "toggle" I meant `CLK` on **and off again** (!). But that was certainly described badly, sorry (I will correct that).
> 
> However, I tried to test the project myself again and couldn't get it to work! I don't really understand what the problem is right now. Unfortunately it is currently impossible to edit chips in the simulator so I cannot debug the problem. I tried to load the project in the [community edition simulator](https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE) (which supposedly has chip editing capability), but it didn't load. I will wait for this issue to be resolved and try again: [DigitalLogicSimCommunity/Digital-Logic-Sim-CE#33](https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/issues/33)

you know. i have seen a bug where NOT gate that exists by its own in order to servere the purpose of being independent power source when built into chip turns off

**Comment by gschwaer** [comment]
Hi, (almost a year later, sorry) I added some instructions to actually run this project. It's not possible to run in the original Digital-Logic-Sim, but in the Community Edition it works in edit mode. The new comment in `Readme.md`:

> Due to https://github.com/gschwaer/Swappy/issues/1 it currently only works in [Digital-Logic-Sim Community Edition](https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE) when using the edit mode: Click the red button on the bottom left, change to COMP > scroll the chips all the way to the right > right click on CPU4 > click VIEW > click the play button at the top center.

I think this should be sufficient to try out this project. Since the original Digital Logic Sim got an update this year that is incompatible with the old project format, I don't think I will maintain this project further. I may archive this repo instead at some point. Feel free to contact me again if this did not fix the issue.
